Quantco/glum

CHANGELOG.rst, setup.py
Checklist
Currently, when we do `pip install glum`, we're not installing run time dependencies. I'm now adding them to setup.py. I'm skipping `tqdm`, because we're treating it as optional:
https://github.com/Quantco/glum/blob/5c06a9067e2d49243c390edd86ca3d41d75257ee/src/glum/_solvers.py#L383-L384
=> Add pip requirements

pyproject.toml
Starting with 2.2.0, cibuildwheel builds wheels for musllinux by default. We will wait until musllinux is supported by numpy before introducing it for glum. See PR #480 for background.
Checklist
=> Skip musllinux wheels

CHANGELOG.rst, pyproject.toml
Because of ABI backward compatibility, building a package with an old version of numpy will work with a more recent version of numpy. We should then always build glum with the oldest supported version of numpy. This was already the case in tabmat but was overlooked in glum.
Checklist
=> use oldest-supported-numpy at build time instead of numpy

environment.yml
I don't know exactly why we pinned sphinx to a specific version. @tbenthompson maybe you remember?
I think this might solve the problem with the new readthedocs PR.
Checklist
=> changed exact pins for minimum versions

environment.yml
Upstream bug was fixed and readthedocs is now successful without the need to pin python.
Checklist
=> [docs] remove python upper bound

environment.yml
The latest dask release does not support the latest version of scikit-learn. This is a quick fix to fix our failing tests.
This fixes #541.
Checklist
=> Temporary sklearn pin to below 1.1 (due to dask)

environment.yml
Closes #546 
This reverts #545 and pins [dask-ml](https://github.com/dask/dask-ml/releases/tag/v2022.5.27) instead.
=> Pin dask-ml instead of scikit-learn

CHANGELOG.rst
Fixing the release pipeline. `cibuildwheel` is now activated in the organization.
Checklist
=> Release 2.2.1

CHANGELOG.rst, src/glum/_glm.py
Closes #589. This PR suggests that we call `tabmat.from_pandas` on any dataframe. In the case that it does not contain any categoricals, we don't drop any levels. 
Checklist
=> Use tm.from_pandas for any pd.dataframe

CHANGELOG.rst, src/glum/_distribution.py, tests/glm/test_glm.py
Fixes #610.
This PR fixes an issue when std_errors is called with a tabmat matrix. The call to `sparse.hstack` is not compatible with tabmat matrices.
Checklist
=> Fix issue with SplitMatrix in `std_errors`

CHANGELOG.rst, src/glum/_cd_fast.pyx, src/glum/_functions.pyx
This removes unused imports from scikit-learn within _cd_fast.pyx. The imports referenced functions that have seen type signature changes in the latest nightly builds of scikit-learn which can cause linking issues when deploying glum in environments with this build. (https://github.com/Quantco/glum/issues/614)
Checklist
=> Removes unused scikit-learn imports from _cd_fast.pyx

.pre-commit-config.yaml
The latest releases don't seem to work with `**kwargs`. Thus pin to the last known working version.
Checklist
=> Pin to working `types-setuptools`

docs/getting_started/getting_started.md, src/glum/_glm.py
Checklist
Motivation
I found it counter-intuitive that the default `alpha=None` actually corresponds to `alpha=1.0`.
I will update docstrings/ documentation to make the connection to the unregularized GLM more explicit.
=> Update documentation for GeneralizedLinearModel

CHANGELOG.rst, src/glum/__init__.py, src/glum/_glm.py, src/glum/_glm_cv.py, src/glum/_link.py, tests/glm/test_glm.py, tests/glm/test_link.py
Checklist
This PR adds a new link function for Binomial models: the complementary log-log (cloglog) link. It is especially useful for modelling interval-censored duration data ([source](https://grodri.github.io/glms/notes/c7s6)).
=> Feat cloglog

CHANGELOG.rst, src/glum/_glm.py
Checklist
In the `GeneralizedLinearRegressor.covariance_matrix` method, the condition number (`numpy.linalg.cond`) of `X` is calculated to make sure it is full rank before proceeding. However, this check is only done if the input is a `DenseMatrix`.
This PR proposes to calculate the condition number of `X.T @ X` instead, which is the square of the condition number of `X`. This approach has two main advantages:
- We can do it for every kind of matrix by leveraging the `.sandwich()` method.
- It is much faster in the case of tall matrices even when `X` is dense. (In fact, for certain inputs, the majority of the runtime of `covariance_matrix()` was spent on the `numpy.linalg.cond(X)` line before this change.)
=> Improve the check for multicollinear columns in `.covariance_matrix()`

.github/workflows/conda-build.sh, .github/workflows/macos-conda-build.sh
We currently still use `conda build`, which is slow.
(NB: we could also re-consider dropping the conda build steps completely, see #473)
=> Use boa to build conda packages in CI

CHANGELOG.rst, src/glum/_glm.py
Checklist
This PR implements a minimal fix for #669. It replaces the (non-pure) `_set_up_and_check_fit_args` method call in `covariance_matrix()` with the side-effectless `check_X_y_tabmat_compliant` function plus a few more lines of code.
The fix does work, but I believe that the underlying issue is a bit deeper, and a proper solution would require some refactoring. Basically, it is not totally clear (at least to me) where the line lies between `_set_up_and_check_fit_args` and `check_X_y_tabmat_compliant`. For example, converting to `MatrixBase` and handling integer arrays is done in the former, while I feel it should belong to the latter.
It would be nice to have a method/function (could be `check_X_y_tabmat_compliant`), after which we can be sure that `X` is a nice, checked …
=> Fix covariance matrix mutating feature names

CHANGELOG.rst, src/glum/_glm.py, src/glum/_glm_cv.py, tests/glm/test_glm.py
Checklist
Add option to store the covariance matrix in the model object when computing it. Furthermore, add a `store_covariance_matrix` parameter to the regressors' constructor, which then automatically estimates and stores the covariance matrix after fitting the model. When a covariance matrix is stored, inference methods can be called without any arguments.
The purpose of this PR is twofold: (1) it makes statistical inference slightly more ergonomic, and (2) it avoids the possibly expensive step of recomputing the covariance matrix when multiple statistical tests are performed. The default is still *not* to store the covariance matrix, and changes are backwards-compatible.
At the moment, only the `std_errors` and `covariance_matrix` methods are affected. A subsequent PR will introduce …
=> Add the option to store the covariance matrix to avoid recomputing it

.github/workflows/build_wheels.yml
Same changes as tabmat: https://github.com/Quantco/tabmat/pull/319
This is the preferred way to authenticate with pypi.
Tested with the tabmat PR. If the reviewer wants we can run the same tests in glum.
Checklist
=> Trusted publisher

src/glum/_glm.py
Relases 2.2 and 2.6 added instantiation attributes to the `GeneralizedLinearRegressor` (`drop_first`, `expected_information` and `robust`), which breaks child classes and pickles. This PR adjusts the code so the new attributes are optional.
=> Improve backwards compatibility

.github/workflows/daily.yml, src/glum/_distribution.py, src/glum/_glm.py, src/glum/_glm_cv.py, src/glum/_solvers.py, src/glum/_util.py, src/glum_benchmarks/orig_sklearn_fork/_glm.py, tests/glm/test_glm.py
Fixing glum to support numpy 2.0. Here is a summary of the changes:
- directly support numpy 2.0:  e.g. `np.Inf` -> `np.inf`
- also use a nightly install of pyarrow (since the stable version doesn't support numpy 2.0)
- some weird changes that should be monitored: statsmodels results are returned as a 2d array while we are using 1d array. The test used to work but now fails. Seems to now be okay with both numpy 2.0 and 1.26, so the likely culprit is probably that before numpy 2.0, [[a]] == [a].
Checklist
=> Fix nightly 2.0

.github/workflows/daily.yml, src/glum/_distribution.py, src/glum/_glm.py, src/glum/_glm_cv.py, src/glum/_solvers.py, src/glum/_util.py, src/glum_benchmarks/orig_sklearn_fork/_glm.py, tests/glm/test_glm.py
[scientific-python-nightly-wheels](https://pypi.anaconda.org/scientific-python-nightly-wheels/simple/) is a lot more up to date than [scipy-wheels-nightly](https://pypi.anaconda.org/scipy-wheels-nightly/simple/scikit-learn/).
CI failure is because of https://github.com/Quantco/glum/issues/714.
=> Update mirror for nightlies

src/glum/_functions.pyx
This PR adds the reference paper for the Tweedie log-likelihood calculation.
Checklist
=> MNT add reference to _tweedie_normalization

CHANGELOG.rst, setup.py, src/glum/_cd_fast.pyx, src/glum/_functions.pyx
Fixes #721.
With cython 3, a major change in the way functions deal with exceptions happened. Before cython 3, if a function didn't have an explicit handling of exception, exceptions were ignored. With cython 3, the default is for a function to always propagate. This leads to a significant performance hit for us. This PR reverts to cython <3 behavior by using the `legacy_implicit_noexcept` compiler directive.
At the same time, I moved the compiler directives from a comment at the top of the cython files and centralized them in the setup.py file.
Testing with the code snippet in the linked issue gives me back the old performance (around 2ms)
Checklist
=> Fix cython performance regression

CHANGELOG.rst, src/glum/_solvers.py
This PR adds a 2. convergence check based on gradients in the line search. This can deal with tiny loss improvements.
This is taken from https://github.com/scikit-learn/scikit-learn/blob/9621539a9defe86ff55c890d5f2475f42697604f/sklearn/linear_model/_glm/_newton_solver.py#L263.
This might help with some of the tests in #723.
Checklist
=> ENH deal with tiny loss improvements in line search

src/glum/_glm.py
This PR removes two unnecessary pieces that made it back to the v3 branch:
- Variable name creation in glum, which is unnecessary becaue tabmat v4 does it internally. Also leads to a test failure in `tests/glm/test_glm.py::test_dropping_distinct_categorical_column`.
- Duplicate call of `check_array_tabmat_compliant` in `predict` (it already calls it via `linear_predictor`).
=> Remove code that is not needed in tabmat v4 / glum v3

tests/glm/test_glm.py
`test_formula` compares a `GeneralizedLinearRegressor` set up with a `formula` argument to one that receives an externally created model matrix via `formulaic.model_matrix`. The test used to fail for one case because the full rank check in the externally created model matrix did not take into account whether the formula implied an intercept or not.
=> Fix formula test: consider presence of intercept in full rankness check when constructing the model matrix externally

src/glum/_glm.py, tests/glm/test_glm.py
Checklist
Currently, the categorical expansion does not take into account the fact that for certain categoricals, an extra (missing) level will be created. This PR fixes the bug.
Note: relies on #748, only merge after that is merged.
=> Correctly expand penalties with categoricals and `cat_missing_method="convert"`

src/glum/_glm.py
So that, in v3, we can still use models that were trained on glum < 3.0.
=> Do not fail when an estimator misses class members that are new in v3

CHANGELOG.rst, src/glum/_glm.py, tests/glm/golden_master/simulation_gm.json, tests/glm/test_distribution.py, tests/glm/test_glm.py, tests/glm/test_golden_master.py
See discussion on https://github.com/Quantco/glum/issues/728.
Checklist
=> No regularization as default

CHANGELOG.rst, src/glum/_glm.py, src/glum/_glm_cv.py, src/glum/_util.py, tests/glm/test_glm.py
The warnings reflect the current state of #764 and #677, should be updated accordingly if we make changes.
Checklist
=> Add future warnings about breaking changes in 3.0.0

CHANGELOG.rst
A release would help disseminate [warnings about breaking changes](https://github.com/Quantco/glum/pull/765) in 3.0.0.
Checklist
=> Update CHANGELOG for release

src/glum_benchmarks/data/create_insurance.py
Sklearn's `ColumnTransformer` now expects `n_samples` as non-optional keyword argument, see [here](https://github.com/scikit-learn/scikit-learn/commit/4a28ba34af9a042dd4c146b463d17c273903c2c0).
=> Daily run failure: add `n_samples` keyword argument to `ColumnTransformer` in benchmarks

CHANGELOG.rst, src/glum/_glm.py, src/glum/_glm_cv.py, tests/glm/test_glm.py
See the comments starting [here](https://github.com/Quantco/glum/pull/677#issuecomment-1939370595). I also added `offset` to the possibly positional arguments to establish a rule "anything but the data that goes into estimation or prediction must be passed as a keyword." Please let me know if you prefer a different convention.
Checklist
=> Make arguments to public methods except `X`, `y`, `sample_weight` and `offset` keyword-only and make initialization keyword-only

CHANGELOG.rst, pyproject.toml, src/glum/_distribution.py, src/glum/_functions.pyx, src/glum/_glm.py, src/glum/_link.py, tests/glm/test_distribution.py, tests/glm/test_link.py
This PR restructures the distributions to avoid diamond inheritance -- i.e. the gamma, inverse Gaussian, normal and Poisson distributions no longer inherit from the Tweedie distribution. Because it is often convenient to test whether a distribution belongs to the Tweedie family, I added a `to_tweedie` method to the base class, which allows users to recover the Tweedie representation of a family if it exists. (I added an equivalent method to `Link`.)
Because it is a breaking change, the base branch is `glum_v3`.
Some free riders:
- `ExponentialDispersionModel.in_y_range` has been cleaned up.
- The documentation of the different distributions has been cleaned up and simplified.
- Excessively restrictive type hints have been removed. A few new hints have been added.
- Cython functions for …
=> Restructure distributions

.github/workflows/daily.yml
Checklist
I suggest to skip testing the nightly build with numpy 2.0 until we figure out how to fix the current errors. This will make the CI pass again for many PR that had nothing to do with numpy but were still failing the nightly job.
=> Skip numpy in nightly

src/glum/_glm.py, src/glum/_util.py
A little clean-up:
- `_expand_categorical_penalties` doesn't leverage the scope at all, so it doesn't need to be an inner function.
- `_is_contiguous` is self-standing, so it doesn't need to be a method.
- No reason to use `chain` anywhere.
=> Move helpers into `_utils`

tests/glm/test_glm.py
Checklist
This change should fix the `formulaic.errors.FormulaMaterializerNotFoundError: No materializer has been registered for input type 'pandas.DataFrame'. Available input types are: set().` errors in the nightlies run. The underlying cause is that the current version of formulaic has some issues with pandas 3.0, and `model_matrix` does not work without selecting a materializer explicitly.
IMO being explicit is not a bad idea anyway, so we can fix the test instead of waiting for a formulaic update.
=> Fix `test_formula` for pandas 3.0 nightly

CHANGELOG.rst, src/glum/_glm.py, tests/glm/test_glm.py
The code mistakenly used `feature_names` instead of term names there.
Checklist
=> Fix bug in Wald test with term names without intercept

.github/workflows/ci.yml, src/glum/_glm.py
The development version doesn't count as 1.6 or newer, as it turns out.
This PR also adds the nightly tests to CI to avoid a repeat.
Closes #819.
=> Rename argument for SKL compatibility

src/glum/_glm_cv.py, tests/glm/test_cv_glm.py
Checklist
`GeneralizedLinearRegressorCV` was already prepared to handle formulas in glum 3.0, but the function signature was missed. This PR fixes it and adds a test to make sure it does not happen again.
=> Make `y` optional in GeneralizedLinearRegressorCV when using a formula

pixi.lock, pixi.toml, src/glum/_glm.py, src/glum_benchmarks/data/create_insurance.py
Checklist
While using private imports is not a big issue because of the nightly tests, it is [still annoying](https://github.com/Quantco/glum/pull/832#discussion_r1749917380) as the CI of downstream packages might also fail until we follow the upstream changes in scikit-learn. It turns out that we were using surprisingly few private methods and functions from sklearn, so it is feasible to get rid of them. Let me know if I missed any.
=> Don't use private functions and methods from scikit-learn

CHANGELOG.rst, src/glum/_glm.py
=> scikit-learn-compliant error message when the number of input features is different between the fit and predict methods.

.github/workflows/conda-build.yml
Same as https://github.com/Quantco/tabmat/pull/399.
=> Pin micromamba and drop boa

pixi.toml, src/glum/_glm.py
Closes #853.
Is there a reason for which we aren't testing against nightly NumPy?
=> Drop SciPy from nightly CI

README.md, tests/glm/test_glm.py
Checklist
With the change to a default `alpha=0` in glum 3 many of our tests are now using unregularized models. This might cause issues (#863) when e.g. scikit-learn decides to add singular matrices to`sklearn.utils.check_estimator`'s checks. This PR changes the default model in  `tests/test_glm.py` to the old, regularized default.
I also added a badge for ~~nightlies~~ daily tests to the readme so that it's a bit more obvious when the nightlies are failing.
=> Use regularized models in `test_glm`

src/glum/_glm.py
Closes #878.
In CI against the latest scikit-learn version, we're seeing
```
FAILED tests/glm/test_glm.py::test_check_estimator[GeneralizedLinearRegressor-kwargs0] - AssertionError: GeneralizedLinearRegressor is inheriting from mixins in the wrong order. In general, in mixin inheritance, more specialized mixins must come before more general ones. This means, for instance, `BaseEstimator` should be on the right side of most other mixins. You need to change the order so that:
RegressorMixin comes before/left side of BaseEstimator
FAILED tests/glm/test_glm.py::test_check_estimator[GeneralizedLinearRegressorCV-kwargs1] - AssertionError: GeneralizedLinearRegressorCV is inheriting from mixins in the wrong order. In general, in mixin inheritance, more specialized mixins must come before more …
```
=> Change MRO

.readthedocs.yml, pixi.lock, pixi.toml
From python 3.13, the conda-forge version of `pip` won't list `setuptools` and `wheel` as its dependencies. We need those because we are installing `glum` with the `--no-use-pep517`. This PR adds those two dependencies to `pixi.toml`.
Same thing as [tabmat #417](https://github.com/Quantco/tabmat/pull/417).
Checklist
=> Add wheel and setuptools to host-requirements

.ci_support/linux_64_python3.13.____cpython.yaml, .ci_support/linux_aarch64_python3.13.____cpython.yaml, .ci_support/osx_64_python3.13.____cpython.yaml, .ci_support/osx_arm64_python3.13.____cpython.yaml, .ci_support/win_64_python3.13.____cpython.yaml, .github/workflows/ci.yml, .github/workflows/conda-build.yml, .github/workflows/daily.yml, CHANGELOG.rst, pixi.lock, pixi.toml, setup.py, tests/glm/test_glm.py
=> Build and test with Python 3.13

.github/workflows/ci.yml, CHANGELOG.rst, README.md, pixi.toml
Also switch to using a local copy of the dataset in the doctest to avoid #899, #898, etc.
Checklist
=> Prepare for releasing 3.1.1

pixi.toml
`statsmodels` isn't compatible with `pandas>=3` yet, see https://github.com/statsmodels/statsmodels/issues/9614. The PR got merged, but there's no release yet. I'm addressing this by installing statsmodels nightlies.
CI will be red for the nightlies until #944 is merged.
=> Install statsmodels nightlies

pyproject.toml
Follow up to #948.
- I'm explicitly skipping free threading builds on Windows (because they're broken)
- Removed cp36, cp37 and pp, because cibuildwheels warns that they don't need to be skipped anymore (see https://github.com/Quantco/glum/actions/runs/17578618735/job/49929562743#step:4:179)
CI will be red until #944 is merged.
=> Fix cibuildwheels setup
