Quantco/glum

CHANGELOG.rst
src/glum/_glm.py
tests/glm/test_glm.py

Scoring with offsets

---

src/glum/_glm.py
tests/glm/test_distribution.py

With `y > 100` or `power = 1.01`, `scipy.special.wright_bessel` returned infinities, so I couldn't test those.
Closes #481. @lorentzenchr

Test Tweedie normalization with Wright-Bessel

---

.github/workflows/conda-build-linux-main.yml
.github/workflows/tests-macos-main.yml
.github/workflows/tests-win-main.yml

Use correct default branch in workflows

---

.github/workflows/daily.yml

Let's not add to @lbittarello's duties.

Update assignees on failing unit tests

---

.readthedocs.yml
environment.yml

See PR #512 for background. This PR only purpose is to update PR #512 with the latest changes to main.
Checklist

Reimplementation of PR #512 with latest main branch

---

docs/contributing.rst

We shouldn't encourage the user to install it separately. This should be (and is) handled by the `environment.yml`.
Checklist
cc @ivergara

Run `pre-commit install` inside the environment

---

README.md
docs/benchmarks.rst
setup.py

I added badges and I clarified that glum was developed for problems with N >> K in the docs.
Checklist

Badges and docs

---

.pre-commit-config.yaml

Update mypy hook

---

.github/workflows/macos.sh
.github/workflows/pre-commit.sh
.github/workflows/test.sh
.github/workflows/tests-win-main.yml
.github/workflows/tests-win.yml
environment-benchmark.yml

This fixes issue #536. The issue was caused by an update in git and while it's been fixed in recent version of checkout, there are no solution when using a container to run the next commands.
Checklist

Fix issue 536

---

.github/workflows/daily.yml
.github/workflows/test.sh

Closes #550
Bonus: test against scikit-learn nightlies again (closes #506)

Pin setuptools when testing against NumPy nightlies

---

CHANGELOG.rst

Update changelog for 2.1 release

---

setup.py

We introduced the 3.1.0 pin in #526.

Pin tabmat in setup.py

---

.github/workflows/build_wheels.yml
CHANGELOG.rst

Depends on https://github.com/Quantco/tabmat/pull/192
Should close #558

Don't use march=native when building wheel

---

.ci_support/linux_64_python3.10_default.____cpython.yaml
.ci_support/linux_64_python3.10_skylake.____cpython.yaml
.ci_support/osx_64_python3.10_default.____cpython.yaml
.ci_support/osx_64_python3.10_skylake.____cpython.yaml
.ci_support/osx_arm64_python3.10.____cpython.yaml
.ci_support/win_64_python3.10.____cpython.yaml
.github/workflows/build_wheels.yml
.github/workflows/ci.yml
.github/workflows/conda-build-linux-main.yml
.github/workflows/conda-build-macos.yml
.pre-commit-config.yaml
pyproject.toml

Build wheel for python 3.10

---

CHANGELOG.rst

Prepare for 2.2.0 release

---

src/glum/_glm.py
src/glum/_glm_cv.py

Fixes issue #594.
Thanks @david-cortes for raising up the issue. I hope that this fixes it.
Checklist

Fix misleading P1 docs

---

CHANGELOG.rst
src/glum/__init__.py

Export `LogitLink`

---

.github/workflows/build_wheels.yml
CHANGELOG.rst
build_tools/prepare_macos_wheel.sh
pyproject.toml
setup.py

Build wheels for M1

---

.github/workflows/ci.yml
pyproject.toml

We have [tabmat wheels](https://pypi.org/project/tabmat/#files) for 3.11.

Build wheels for Python 3.11

---

.github/workflows/pre-commit.sh

The time to beat is 11 minutes ([last commit on main](https://github.com/Quantco/glum/actions/runs/4499628960/jobs/7917725126)).
_Edit_: New run time is [2 minutes](https://github.com/Quantco/glum/actions/runs/4540237852/jobs/8000932945?pr=624).

Use mamba for pre-commit environments

---

.github/workflows/tests-win.yml
tests/glm/test_glm.py

Fix Windows CI (issue 632)

---

CHANGELOG.rst
src/glum/_glm.py
tests/glm/test_glm.py

Fix bug in `GLR(warm_start=True).fit(X, y)` if `X` has a const. column

---

src/glum/__init__.py

Closes #665 (hopefully). @mlondschien

`pkg_resources` is deprecated

---

CHANGELOG.rst
conda.recipe/meta.yaml
environment.yml
setup.py

Pin tabmat<4.0.0

---

.github/CODEOWNERS

Hi everyone! You're all great! I miss you. =)

Can I be removed from CODEOWNERS?

---

setup.py

Add 3.12 to metadata

---

src/glum/_glm.py

Addressed a `FutureWarning` from Pandas.
Checklist

Fix Pandas FutureWarning

---

.ci_support/linux_64_python3.12.____cpython.yaml
.ci_support/linux_aarch64_python3.12.____cpython.yaml
.ci_support/osx_64_python3.12.____cpython.yaml
.ci_support/osx_arm64_python3.12.____cpython.yaml
.ci_support/win_64_python3.12.____cpython.yaml
.github/workflows/ci.yml
.github/workflows/conda-build.yml
CHANGELOG.rst
pyproject.toml

Build and test with Python 3.12

---

src/glum/_solvers.py
src/glum_benchmarks/data/create_insurance.py

Pre-commit hooks

---

tests/glm/test_glm.py

Test also a varying confidence level in test of coefficient table against statsmodels

---

README.md

I think the formula interface merits a short mention to potential users.

Add illustration of formula interface to example in README

---

src/glum/_glm.py

See https://github.com/Quantco/glum/issues/775.

Explain `scale_predictors` more

---

.github/workflows/ci.yml
.github/workflows/conda-build.yml
environment-macos.yml

Add a different environment for macos

---

environment.yml

This should fix a bug with the latest version of `git`.

Force newer `setuptools_scm`

---

src/glum/_glm.py
src/glum/_glm_cv.py

This PR folds the `initialize_start_params` function into the `_get_start_coef` method, simplifying the code base slightly.

Combine parsing of initial values

---

.github/workflows/build_wheels.yml
CHANGELOG.rst
pyproject.toml

Support for build with numpy 2.0

---

conda.recipe/meta.yaml
pixi.toml
src/glum/_glm.py
tests/glm/performance/test_performance.py

Rename argument for SKL compatibility

---

pixi.toml

Fix build string for newer pixi versions

---

.github/workflows/daily.yml

Only create an issue on daily run failure if its on the main branch

---

.github/CODEOWNERS

I am not actually doing anything here.
Checklist

Remove @xhochy from CODEOWNERS

---

.github/workflows/ci.yml
.github/workflows/daily.yml

Checklist
We were not actually installing the nightly packages in the nightly environment in `ci.yml`.

Fix nightlies tests

---

CHANGELOG.rst
src/glum/_glm.py

closes https://github.com/Quantco/glum/issues/842

Print more informative logs when alpha-search is True

---

CHANGELOG.rst
src/glum/_glm.py
src/glum/_glm_cv.py

Attach `col_means` and `col_stds` to GeneralizedLinearRegressor. 

---

src/glum/_glm.py

Fixes #892. I don't think this needs a changelog entry but lmk if you think otherwise.
Checklist

Set accepts sparse tag to True

---

.github/workflows/ci.yml
.github/workflows/daily.yml

This PR also fixes a bug in the nightly doctest
Checklist

Use latest dependencies in daily/nightly tests

---

README.md

Checklist
As the title says, I added a DOI record for glum. This PR adds the badge to the readme.

add DOI for citation
